export const THEME_WHITE = "white";
export const THEME_BLACK = "black";

export const MODAL_DASHBOARD_EDIT = "MODAL_DASHBOARD_EDIT";
export const MODAL_DASHBOARD_DELETE = "MODAL_DASHBOARD_DELETE";
export const MODAL_TASK_SHOW = "MODAL_TASK_SHOW";
export const MODAL_TASK_EDIT = "MODAL_TASK_EDIT";
export const MODAL_TASK_DELETE = "MODAL_TASK_DELETE";
